import type { Locale } from './types';

const nl = {
  welcome: 'Welkom bij BusApp', question: 'Waarvoor kom je?', busRole: 'Ik rijd met de bus', busRoleHelp: 'Chauffeur of begeleider', parentRole: 'Ik ben ouder', parentRoleHelp: 'Ik heb een buscode',
  back: 'Terug', language: 'Taal', login: 'Inloggen', register: 'Gratis registreren', email: 'E-mailadres', password: 'Wachtwoord', displayName: 'Voornaam', switchAuth: 'Nog geen account?', existingAuth: 'Ik heb al een account', confirmEmail: 'Controleer je e-mail en log daarna in.', freePromise: 'BusApp blijft gratis.',
  createBus: 'Mijn gratis bus aanmaken', firstBus: 'Maak je eerste bus aan', busName: 'Naam van je bus', capacity: 'Aantal plaatsen', startAddress: 'Startadres', endAddress: 'Eindadres (optioneel)', searchAddress: 'Zoek adres', chooseAddress: 'Kies het juiste adres', addressPlaceholder: 'Straat, nummer en gemeente',
  next: 'Volgende', save: 'Opslaan', loading: 'BusApp laden…', error: 'Er ging iets mis.', retry: 'Opnieuw proberen', logout: 'Afmelden', switchMode: 'Andere toegang',
  bus: 'Bus', myBus: 'Mijn bus', route: 'Route', passengers: 'Passagiers', profile: 'Profiel', notifications: 'Meldingen', today: 'Vandaag', privacy: 'Privacy', addresses: 'adressen', children: 'passagiers', vehicleBus: 'Bus', vehicleVan: 'Bestelwagen', vehicleCoach: 'Reisbus',
  addressOne: 'adres', addressMany: 'adressen', stopOne: 'halte', stopMany: 'haltes', passengerOne: 'passagier', passengerMany: 'passagiers', memberOne: 'lid', memberMany: 'leden', codeOne: 'actieve code', codeMany: 'actieve codes',
  routeMissing: 'Route nog niet berekend', routeMissingHelp: 'Voeg je haltes toe en bereken daarna de beste route.', routeEstimate: 'Route-inschatting', estimated: 'Geschatte afstand en reistijd', realRoute: 'Route', mapUnavailable: 'Kaart nog niet beschikbaar', mapUnavailableBody: 'BusApp toont pas een routekaart wanneer echte geografische kaartgegevens beschikbaar zijn.',
  calculateRoute: 'Bereken beste route', addAddress: 'Adres toevoegen', moreOptions: 'Meer opties', fewerOptions: 'Minder opties', routeReady: 'Route klaar', viewRoute: 'Bekijk route', startTrip: 'Start rit', capacityWarning: '{count} passagiers voor {capacity} plaatsen',
  address: 'Adres', passengerCount: 'Aantal passagiers', addNames: 'Namen toevoegen (optioneel)', namesHint: 'Eén beperkte naam per lijn.', add: 'Toevoegen', duplicate: 'Dit adres staat al in de route.',
  manualOrder: 'Zelf kiezen', automaticRoute: 'Automatisch', recalculate: 'Route opnieuw berekenen', bestRoute: 'Beste route', stops: 'haltes', minutes: 'minuten', kilometers: 'km', map: 'Businformatie', start: 'Start', end: 'Eindpunt', dragHint: 'Sleep de haltes of gebruik de knoppen.', routeFailed: 'Route kon niet automatisch berekend worden.', addressesSafe: 'Je adressen zijn veilig bewaard.', tryAgain: 'Opnieuw proberen', manualChoice: 'Zelf volgorde kiezen',
  parentCodes: 'Oudercodes', newPassenger: 'Passagier toevoegen', closeForm: 'Sluiten', passengerDisplayName: 'Voornaam / weergavenaam', parentName: 'Naam ouder', selectPassenger: 'Kies passagier', createCode: 'Toegangscode maken', codeTitle: 'Toegangscode', showCode: 'Toon code', copyCode: 'Kopieer code', newCode: 'Nieuwe code', revokeAll: 'Alle toegangen intrekken', confirmNewCode: 'Nieuwe toegangscode maken? De vorige code werkt daarna niet meer voor nieuwe aanmeldingen.', codeCopied: 'Code gekopieerd', parentCode: 'Buscode', codePlaceholder: 'XXXX-XXXX-XXXX', openBus: 'Open mijn bus', invalidCode: 'Deze code is niet geldig. Controleer de code of vraag een nieuwe aan je chauffeur.', noPassengers: 'Nog geen passagiers', noPassengersHelp: 'Voeg een passagier toe zodra je eerste halte klaarstaat.', noStops: 'Nog geen haltes', noStopsHelp: 'Voeg je eerste halte toe en BusApp helpt je daarna de route voorbereiden.',
  hello: 'Hallo', onWay: 'De bus is onderweg', almostThere: 'Bijna bij jouw halte', boarding: 'Klaar om te vertrekken', arrived: 'De bus is aangekomen', noActiveTrip: 'De bus rijdt nu niet.', yourStop: 'Jouw halte', approximately: 'Nog ongeveer', onBus: 'Op de bus', expected: 'Wordt verwacht', missed: 'Niet aanwezig', dropped: 'Afgezet', privacyTitle: 'Volg de bus, niet de kinderen', privacyBody: 'Je ziet alleen de informatie die voor jou nodig is.',
  nextStop: 'Volgende halte', expectedAtStop: 'verwacht', gpsActive: 'Bus-GPS actief', gpsDenied: 'Locatietoegang is nodig tijdens de rit.', startDriving: 'Vertrek', arrive: 'Aankomen', complete: 'Rit voltooien', cancel: 'Rit annuleren', stopComplete: 'Halte klaar', approaching: 'Naderen', enablePush: 'Meldingen inschakelen', pushEnabled: 'Meldingen zijn actief', noNotifications: 'Nog geen meldingen.', offline: 'Offline — acties worden opnieuw geprobeerd zodra je verbinding hebt.', driverSafety: 'Tijdens het rijden blijven alleen grote, noodzakelijke acties zichtbaar.', routeStale: 'De route moet opnieuw berekend worden.',
  avatar: 'Kleur', chooseAvatar: 'Kies een kleur', avatarBlue: 'Luchtblauw', avatarGreen: 'Mint', avatarPurple: 'Lavendel', avatarOrange: 'Perzik', avatarRose: 'Roze',
  moveUp: 'Naar boven', moveDown: 'Naar beneden', decrease: 'Verminderen', increase: 'Verhogen', tripProgress: 'Voortgang van de rit', edit: 'Bewerken', copied: 'Gekopieerd', members: 'leden', currentBusPosition: 'Laatste busupdate', ownStopPosition: 'Jouw halte', languageDutch: 'Nederlands', languageFrench: 'Frans', interfaceLanguage: 'Taal van de app', busLanguage: 'Taal voor busmeldingen', chooseProfileAvatar: 'Kies je profiel', choosePassengerAvatar: 'Kies een passagiersavatar', chooseBusAvatar: 'Kies je bus', builtInAvatars: 'Illustraties', uploadPhoto: 'Foto uploaden', changePhoto: 'Foto wijzigen', photoHint: 'JPG, PNG of WebP · maximaal 5 MB', photoPreview: 'Voorbeeld en uitsnede', zoom: 'Zoom', profileSaved: 'Profiel opgeslagen', busProfile: 'Busprofiel', yourProfile: 'Jouw profiel', avatarUpdated: 'Avatar bijgewerkt', cancelPhoto: 'Annuleren', ownerOnly: 'Je hebt geen toestemming om het busprofiel te wijzigen.',
  editProfile: 'Profiel aanpassen', editBus: 'Bus aanpassen', editAvatar: 'Avatar aanpassen', cancelEdit: 'Annuleren', removePhoto: 'Foto verwijderen',
  roleDriver: 'Chauffeur', roleAttendant: 'Begeleider', roleOwner: 'Chauffeur', roleParent: 'Ouder',
  myBusSection: 'Mijn bus', yourBus: 'Jouw bus', viewBus: 'Bekijk bus', backToBus: 'Terug', busToday: 'Jouw bus vandaag', noStaffAssigned: 'Nog geen chauffeur toegewezen.',
  profileSaveFailed: 'Je profiel kon niet worden opgeslagen. Probeer opnieuw.', busSaveFailed: 'De busfoto kon niet worden opgeslagen. Probeer opnieuw.', avatarSaveFailed: 'De avatar kon niet worden opgeslagen. Probeer opnieuw.',
  nameRequired: 'Vul een naam in.', profilePerson: 'Dit is jouw persoonlijke profiel, niet je bus.',
} as const;

const fr: Record<keyof typeof nl, string> = {
  welcome: 'Bienvenue dans BusApp', question: 'Pourquoi êtes-vous ici ?', busRole: 'Je suis dans le bus', busRoleHelp: 'Chauffeur ou accompagnateur', parentRole: 'Je suis parent', parentRoleHelp: "J'ai un code bus",
  back: 'Retour', language: 'Langue', login: 'Se connecter', register: "S'inscrire gratuitement", email: 'Adresse e-mail', password: 'Mot de passe', displayName: 'Prénom', switchAuth: 'Pas encore de compte ?', existingAuth: "J'ai déjà un compte", confirmEmail: 'Consultez votre e-mail puis connectez-vous.', freePromise: 'BusApp reste gratuit.',
  createBus: 'Créer mon bus gratuit', firstBus: 'Créez votre premier bus', busName: 'Nom du bus', capacity: 'Nombre de places', startAddress: 'Adresse de départ', endAddress: "Adresse d'arrivée (facultatif)", searchAddress: "Rechercher l'adresse", chooseAddress: 'Choisissez la bonne adresse', addressPlaceholder: 'Rue, numéro et commune',
  next: 'Suivant', save: 'Enregistrer', loading: 'Chargement de BusApp…', error: "Une erreur s'est produite.", retry: 'Réessayer', logout: 'Se déconnecter', switchMode: "Changer d'accès",
  bus: 'Bus', myBus: 'Mon bus', route: 'Itinéraire', passengers: 'Passagers', profile: 'Profil', notifications: 'Notifications', today: "Aujourd'hui", privacy: 'Confidentialité', addresses: 'adresses', children: 'passagers', vehicleBus: 'Bus', vehicleVan: 'Minibus', vehicleCoach: 'Autocar',
  addressOne: 'adresse', addressMany: 'adresses', stopOne: 'arrêt', stopMany: 'arrêts', passengerOne: 'passager', passengerMany: 'passagers', memberOne: 'membre', memberMany: 'membres', codeOne: 'code actif', codeMany: 'codes actifs',
  routeMissing: "Itinéraire pas encore calculé", routeMissingHelp: 'Ajoutez vos arrêts puis calculez le meilleur itinéraire.', routeEstimate: "Estimation d'itinéraire", estimated: 'Distance et durée estimées', realRoute: 'Itinéraire', mapUnavailable: 'Carte pas encore disponible', mapUnavailableBody: "BusApp affichera une carte uniquement lorsque de vraies données cartographiques seront disponibles.",
  calculateRoute: 'Calculer le meilleur itinéraire', addAddress: 'Ajouter une adresse', moreOptions: "Plus d'options", fewerOptions: "Moins d'options", routeReady: 'Itinéraire prêt', viewRoute: "Voir l'itinéraire", startTrip: 'Démarrer le trajet', capacityWarning: '{count} passagers pour {capacity} places',
  address: 'Adresse', passengerCount: 'Nombre de passagers', addNames: 'Ajouter des noms (facultatif)', namesHint: 'Un nom limité par ligne.', add: 'Ajouter', duplicate: "Cette adresse figure déjà dans l'itinéraire.",
  manualOrder: 'Choisir moi-même', automaticRoute: 'Automatique', recalculate: "Recalculer l'itinéraire", bestRoute: 'Meilleur itinéraire', stops: 'arrêts', minutes: 'minutes', kilometers: 'km', map: 'Informations du bus', start: 'Départ', end: 'Arrivée', dragHint: 'Glissez les arrêts ou utilisez les boutons.', routeFailed: "L'itinéraire n'a pas pu être calculé automatiquement.", addressesSafe: 'Vos adresses sont bien enregistrées.', tryAgain: 'Réessayer', manualChoice: "Choisir l'ordre moi-même",
  parentCodes: 'Codes parents', newPassenger: 'Ajouter un passager', closeForm: 'Fermer', passengerDisplayName: 'Nom affiché', parentName: 'Nom du parent', selectPassenger: 'Choisir un passager', createCode: "Créer le code d'accès", codeTitle: "Code d'accès", showCode: 'Afficher le code', copyCode: 'Copier le code', newCode: 'Nouveau code', revokeAll: 'Révoquer tous les accès', confirmNewCode: "Créer un nouveau code ? L'ancien ne permettra plus de nouvelles connexions.", codeCopied: 'Code copié', parentCode: 'Code bus', codePlaceholder: 'XXXX-XXXX-XXXX', openBus: 'Ouvrir mon bus', invalidCode: "Ce code n'est pas valide. Vérifiez-le ou demandez-en un nouveau à votre chauffeur.", noPassengers: 'Aucun passager', noPassengersHelp: 'Ajoutez un passager dès que votre premier arrêt est prêt.', noStops: 'Aucun arrêt', noStopsHelp: 'Ajoutez votre premier arrêt et BusApp vous aidera ensuite à préparer le trajet.',
  hello: 'Bonjour', onWay: 'Le bus est en route', almostThere: 'Presque à votre arrêt', boarding: 'Prêt à partir', arrived: 'Le bus est arrivé', noActiveTrip: 'Le bus ne circule pas actuellement.', yourStop: 'Votre arrêt', approximately: 'Encore environ', onBus: 'À bord', expected: 'Attendu', missed: 'Absent', dropped: 'Déposé', privacyTitle: 'Suivez le bus, pas les enfants', privacyBody: 'Vous voyez uniquement les informations qui vous sont nécessaires.',
  nextStop: 'Prochain arrêt', expectedAtStop: 'attendus', gpsActive: 'GPS du bus actif', gpsDenied: 'La localisation est nécessaire pendant le trajet.', startDriving: 'Partir', arrive: 'Arriver', complete: 'Terminer le trajet', cancel: 'Annuler le trajet', stopComplete: 'Arrêt terminé', approaching: 'Approche', enablePush: 'Activer les notifications', pushEnabled: 'Notifications actives', noNotifications: 'Aucune notification.', offline: 'Hors ligne — les actions seront réessayées au retour de la connexion.', driverSafety: 'Pendant la conduite, seules les grandes actions indispensables restent visibles.', routeStale: "L'itinéraire doit être recalculé.",
  avatar: 'Couleur', chooseAvatar: 'Choisir une couleur', avatarBlue: 'Bleu ciel', avatarGreen: 'Menthe', avatarPurple: 'Lavande', avatarOrange: 'Pêche', avatarRose: 'Rose',
  moveUp: 'Monter', moveDown: 'Descendre', decrease: 'Diminuer', increase: 'Augmenter', tripProgress: 'Progression du trajet', edit: 'Modifier', copied: 'Copié', members: 'membres', currentBusPosition: 'Dernière mise à jour du bus', ownStopPosition: 'Votre arrêt', languageDutch: 'Néerlandais', languageFrench: 'Français', interfaceLanguage: "Langue de l’application", busLanguage: 'Langue des notifications du bus', chooseProfileAvatar: 'Choisissez votre profil', choosePassengerAvatar: 'Choisissez un avatar passager', chooseBusAvatar: 'Choisissez votre bus', builtInAvatars: 'Illustrations', uploadPhoto: 'Importer une photo', changePhoto: 'Changer la photo', photoHint: 'JPG, PNG ou WebP · 5 Mo maximum', photoPreview: 'Aperçu et cadrage', zoom: 'Zoom', profileSaved: 'Profil enregistré', busProfile: 'Profil du bus', yourProfile: 'Votre profil', avatarUpdated: 'Avatar mis à jour', cancelPhoto: 'Annuler', ownerOnly: "Vous n'avez pas l'autorisation de modifier le profil du bus.",
  editProfile: 'Modifier le profil', editBus: 'Modifier le bus', editAvatar: "Modifier l'avatar", cancelEdit: 'Annuler', removePhoto: 'Supprimer la photo',
  roleDriver: 'Conducteur', roleAttendant: 'Accompagnateur', roleOwner: 'Conducteur', roleParent: 'Parent',
  myBusSection: 'Mon bus', yourBus: 'Votre bus', viewBus: 'Voir le bus', backToBus: 'Retour', busToday: "Votre bus aujourd'hui", noStaffAssigned: 'Aucun conducteur assigné pour le moment.',
  profileSaveFailed: "Votre profil n'a pas pu être enregistré. Réessayez.", busSaveFailed: "La photo du bus n'a pas pu être enregistrée. Réessayez.", avatarSaveFailed: "L'avatar n'a pas pu être enregistré. Réessayez.",
  nameRequired: 'Indiquez un nom.', profilePerson: "Ceci est votre profil personnel, pas votre bus.",
};

const dictionary: Record<Locale, Record<keyof typeof nl, string>> = { nl, fr };
export type TranslationKey = keyof typeof nl;
export function translate(locale: Locale, key: TranslationKey, values: Record<string, string | number> = {}): string {
  let value = dictionary[locale][key];
  for (const [name, replacement] of Object.entries(values)) value = value.replace(`{${name}}`, String(replacement));
  return value;
}
