import type { Locale } from './types';

const nl = {
  welcome: 'Welkom bij BusApp', question: 'Waarvoor kom je?', busRole: 'Ik rijd met de bus', busRoleHelp: 'Chauffeur of begeleider', parentRole: 'Ik ben ouder', parentRoleHelp: 'Ik heb een buscode',
  back: 'Terug', language: 'Taal', login: 'Inloggen', register: 'Gratis registreren', email: 'E-mailadres', password: 'Wachtwoord', displayName: 'Voornaam', switchAuth: 'Nog geen account?', existingAuth: 'Ik heb al een account', confirmEmail: 'Controleer je e-mail en log daarna in.', freePromise: 'BusApp blijft gratis.',
  createBus: 'Mijn gratis bus aanmaken', firstBus: 'Maak je eerste bus aan', busName: 'Naam van je bus', capacity: 'Aantal plaatsen', startAddress: 'Startadres', endAddress: 'Eindadres (optioneel)', searchAddress: 'Zoek adres', chooseAddress: 'Kies het juiste adres', addressPlaceholder: 'Straat, nummer en gemeente',
  next: 'Volgende', save: 'Opslaan', loading: 'BusApp laden…', error: 'Er ging iets mis.', retry: 'Opnieuw proberen', logout: 'Afmelden', switchMode: 'Andere toegang',
  bus: 'Bus', route: 'Route', passengers: 'Passagiers', profile: 'Profiel', notifications: 'Meldingen', addresses: 'adressen', children: 'passagiers',
  routeMissing: 'Route nog niet berekend', routeMissingHelp: 'Voeg je haltes toe en bereken daarna de beste route.', routeEstimate: 'Route-inschatting', estimated: 'Geschatte afstand en reistijd', realRoute: 'Route', mapUnavailable: 'Kaart nog niet beschikbaar', mapUnavailableBody: 'BusApp toont pas een routekaart wanneer echte geografische kaartgegevens beschikbaar zijn.',
  calculateRoute: 'Bereken beste route', addAddress: 'Adres toevoegen', moreOptions: 'Meer opties', routeReady: 'Routegegevens klaar', viewRoute: 'Bekijk routegegevens', startTrip: 'Start rit', capacityWarning: '{count} passagiers voor {capacity} plaatsen',
  address: 'Adres', passengerCount: 'Aantal passagiers', addNames: 'Namen toevoegen (optioneel)', namesHint: 'Eén beperkte naam per lijn.', add: 'Toevoegen', duplicate: 'Dit adres staat al in de route.',
  manualOrder: 'Zelf volgorde aanpassen', automaticRoute: 'Automatische route', recalculate: 'Route opnieuw berekenen', bestRoute: 'Beste route', stops: 'haltes', minutes: 'minuten', kilometers: 'km', map: 'Businformatie', start: 'Start', end: 'Eindpunt', dragHint: 'Sleep de haltes of gebruik de knoppen.', routeFailed: 'Route kon niet automatisch berekend worden.', addressesSafe: 'Je adressen zijn veilig bewaard.', tryAgain: 'Opnieuw proberen', manualChoice: 'Zelf volgorde kiezen',
  parentCodes: 'Oudercodes', newPassenger: 'Passagier toevoegen', parentName: 'Naam ouder', selectPassenger: 'Kies passagier', createCode: 'Toegangscode maken', codeTitle: 'Toegangscode', showCode: 'Toon code', copyCode: 'Kopieer code', newCode: 'Nieuwe code', revokeAll: 'Alle toegangen intrekken', confirmNewCode: 'Nieuwe toegangscode maken? De vorige code werkt daarna niet meer voor nieuwe aanmeldingen.', codeCopied: 'Code gekopieerd', parentCode: 'Buscode', codePlaceholder: 'XXXX-XXXX-XXXX', openBus: 'Open mijn bus', invalidCode: 'Deze code is niet geldig. Controleer de code of vraag een nieuwe aan je chauffeur.',
  hello: 'Hallo', onWay: 'Onderweg', boarding: 'Instappen', arrived: 'Aangekomen', noActiveTrip: 'Er is nu geen actieve rit.', yourStop: 'Jouw halte', approximately: 'Nog ongeveer', onBus: 'Op de bus', expected: 'Verwacht', missed: 'Niet aanwezig', dropped: 'Afgezet', privacyTitle: 'Volg de bus, niet de kinderen', privacyBody: 'Je ziet alleen jouw passagier, jouw halte en de relevante businformatie.',
  nextStop: 'Volgende halte', expectedAtStop: 'verwacht', gpsActive: 'Bus-GPS actief', gpsDenied: 'Locatietoegang is nodig tijdens de rit.', startDriving: 'Vertrek', arrive: 'Aankomen', complete: 'Rit voltooien', cancel: 'Rit annuleren', stopComplete: 'Halte klaar', approaching: 'Naderen', enablePush: 'Meldingen inschakelen', pushEnabled: 'Meldingen zijn actief', noNotifications: 'Nog geen meldingen.', offline: 'Offline — acties worden opnieuw geprobeerd zodra je verbinding hebt.', driverSafety: 'Tijdens het rijden blijven alleen grote, noodzakelijke acties zichtbaar.', routeStale: 'De route moet opnieuw berekend worden.',
  avatar: 'Avatarstijl', avatarBlue: 'Blauw', avatarGreen: 'Groen', avatarPurple: 'Paars', avatarOrange: 'Oranje', avatarRose: 'Roze',
  moveUp: 'Naar boven', moveDown: 'Naar beneden', decrease: 'Verminderen', increase: 'Verhogen', tripProgress: 'Voortgang van de rit', edit: 'Bewerken', copied: 'Gekopieerd', members: 'leden', currentBusPosition: 'Huidige buspositie', ownStopPosition: 'Jouw halte',
} as const;

const fr: Record<keyof typeof nl, string> = {
  welcome: 'Bienvenue dans BusApp', question: 'Pourquoi êtes-vous ici ?', busRole: 'Je suis dans le bus', busRoleHelp: 'Chauffeur ou accompagnateur', parentRole: 'Je suis parent', parentRoleHelp: "J'ai un code bus",
  back: 'Retour', language: 'Langue', login: 'Se connecter', register: "S'inscrire gratuitement", email: 'Adresse e-mail', password: 'Mot de passe', displayName: 'Prénom', switchAuth: 'Pas encore de compte ?', existingAuth: "J'ai déjà un compte", confirmEmail: 'Consultez votre e-mail puis connectez-vous.', freePromise: 'BusApp reste gratuit.',
  createBus: 'Créer mon bus gratuit', firstBus: 'Créez votre premier bus', busName: 'Nom du bus', capacity: 'Nombre de places', startAddress: 'Adresse de départ', endAddress: "Adresse d'arrivée (facultatif)", searchAddress: "Rechercher l'adresse", chooseAddress: 'Choisissez la bonne adresse', addressPlaceholder: 'Rue, numéro et commune',
  next: 'Suivant', save: 'Enregistrer', loading: 'Chargement de BusApp…', error: "Une erreur s'est produite.", retry: 'Réessayer', logout: 'Se déconnecter', switchMode: "Changer d'accès",
  bus: 'Bus', route: 'Itinéraire', passengers: 'Passagers', profile: 'Profil', notifications: 'Notifications', addresses: 'adresses', children: 'passagers',
  routeMissing: "Itinéraire pas encore calculé", routeMissingHelp: 'Ajoutez vos arrêts puis calculez le meilleur itinéraire.', routeEstimate: "Estimation d'itinéraire", estimated: 'Distance et durée estimées', realRoute: 'Itinéraire', mapUnavailable: 'Carte pas encore disponible', mapUnavailableBody: "BusApp affichera une carte uniquement lorsque de vraies données cartographiques seront disponibles.",
  calculateRoute: 'Calculer le meilleur itinéraire', addAddress: 'Ajouter une adresse', moreOptions: "Plus d'options", routeReady: "Données d'itinéraire prêtes", viewRoute: "Voir les données d'itinéraire", startTrip: 'Démarrer le trajet', capacityWarning: '{count} passagers pour {capacity} places',
  address: 'Adresse', passengerCount: 'Nombre de passagers', addNames: 'Ajouter des noms (facultatif)', namesHint: 'Un nom limité par ligne.', add: 'Ajouter', duplicate: "Cette adresse figure déjà dans l'itinéraire.",
  manualOrder: "Modifier l'ordre moi-même", automaticRoute: 'Itinéraire automatique', recalculate: "Recalculer l'itinéraire", bestRoute: 'Meilleur itinéraire', stops: 'arrêts', minutes: 'minutes', kilometers: 'km', map: 'Informations du bus', start: 'Départ', end: 'Arrivée', dragHint: 'Glissez les arrêts ou utilisez les boutons.', routeFailed: "L'itinéraire n'a pas pu être calculé automatiquement.", addressesSafe: 'Vos adresses sont bien enregistrées.', tryAgain: 'Réessayer', manualChoice: "Choisir l'ordre moi-même",
  parentCodes: 'Codes parents', newPassenger: 'Ajouter un passager', parentName: 'Prénom du parent', selectPassenger: 'Choisir un passager', createCode: "Créer le code d'accès", codeTitle: "Code d'accès", showCode: 'Afficher le code', copyCode: 'Copier le code', newCode: 'Nouveau code', revokeAll: 'Révoquer tous les accès', confirmNewCode: "Créer un nouveau code ? L'ancien ne permettra plus de nouvelles connexions.", codeCopied: 'Code copié', parentCode: 'Code bus', codePlaceholder: 'XXXX-XXXX-XXXX', openBus: 'Ouvrir mon bus', invalidCode: "Ce code n'est pas valide. Vérifiez-le ou demandez-en un nouveau à votre chauffeur.",
  hello: 'Bonjour', onWay: 'En route', boarding: 'Embarquement', arrived: 'Arrivé', noActiveTrip: "Il n'y a pas de trajet actif.", yourStop: 'Votre arrêt', approximately: 'Encore environ', onBus: 'À bord', expected: 'Attendu', missed: 'Absent', dropped: 'Déposé', privacyTitle: 'Suivez le bus, pas les enfants', privacyBody: 'Vous voyez uniquement votre passager, votre arrêt et les informations utiles du bus.',
  nextStop: 'Prochain arrêt', expectedAtStop: 'attendus', gpsActive: 'GPS du bus actif', gpsDenied: 'La localisation est nécessaire pendant le trajet.', startDriving: 'Partir', arrive: 'Arriver', complete: 'Terminer le trajet', cancel: 'Annuler le trajet', stopComplete: 'Arrêt terminé', approaching: 'Approche', enablePush: 'Activer les notifications', pushEnabled: 'Notifications actives', noNotifications: 'Aucune notification.', offline: 'Hors ligne — les actions seront réessayées au retour de la connexion.', driverSafety: 'Pendant la conduite, seules les grandes actions indispensables restent visibles.', routeStale: "L'itinéraire doit être recalculé.",
  avatar: "Style d'avatar", avatarBlue: 'Bleu', avatarGreen: 'Vert', avatarPurple: 'Violet', avatarOrange: 'Orange', avatarRose: 'Rose',
  moveUp: 'Monter', moveDown: 'Descendre', decrease: 'Diminuer', increase: 'Augmenter', tripProgress: 'Progression du trajet', edit: 'Modifier', copied: 'Copié', members: 'membres', currentBusPosition: 'Position actuelle du bus', ownStopPosition: 'Votre arrêt',
};

const dictionary: Record<Locale, Record<keyof typeof nl, string>> = { nl, fr };
export type TranslationKey = keyof typeof nl;
export function translate(locale: Locale, key: TranslationKey, values: Record<string, string | number> = {}): string {
  let value = dictionary[locale][key];
  for (const [name, replacement] of Object.entries(values)) value = value.replace(`{${name}}`, String(replacement));
  return value;
}
